<a href="https://colab.research.google.com/github/Krishna-Bhatt/DeepLearning/blob/main/00_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)


2.4.1


In [ ]:
sc = tf.constant(7)
sc

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
sc.ndim

0

In [ ]:
vc = tf.constant([1,1])
vc

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
vc.ndim

1

In [ ]:
mt = tf.constant([[1,2],[3,4]])
mt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
mt.ndim

2

In [ ]:
amt = tf.constant([[10,7],[3,2]],dtype = tf.float16)
amt

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.]], dtype=float16)>

In [ ]:
c = tf.Variable([10,7])
t = tf.constant([10,7])
c,t

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
c[0].assign(70)
c

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([70,  7], dtype=int32)>

In [ ]:
ran = tf.random.Generator.from_seed(42)
ran = ran.normal(shape=(3,2))


In [ ]:
ns = tf.constant([[10,7],[3,5],[2,8]])
ns


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  8]], dtype=int32)>

In [ ]:
tf.random.shuffle(ns,42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  8],
       [ 3,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.ones([10,7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

Diff btwn numpy and tf:
tf runs faster on GPU
***italicized text***

In [ ]:
import numpy as np
nA = np.arange(1,25,dtype=np.int32)
nA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(nA,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
r4 = tf.zeros(shape=[2,3,4,5])
r4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
r4.shape,r4.ndim,tf.size(r4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print(r4.dtype)

<dtype: 'float32'>


In [ ]:
x = r4[:2,:2,:2,:2]
x

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
r4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r2 = tf.constant([[1,2],[3,4]])
r3 = r2[...,tf.newaxis]
r3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
t = tf.constant([[10,7],[3,4]])
t+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
t*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.matmul(t,t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
x = tf.constant([[1,2],[3,4],[5,6]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
y = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 57, 66],
       [60, 72, 84]], dtype=int32)>

In [ ]:
B = tf.constant([1.7,4,5])
B.dtype

tf.float32

In [ ]:
d = tf.cast(B,dtype=tf.float16)
d

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.7, 4. , 5. ], dtype=float16)>

# Aggregations

In [ ]:
tf.abs(B)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.7, 4. , 5. ], dtype=float16)>

In [ ]:
e = tf.constant(np.random.randint(0,100,size=50))

e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([30, 94, 40, 45, 92, 55, 44, 39, 98, 96,  0, 23, 76, 36, 51, 75, 81,
       98, 79, 37, 20, 92, 93, 47, 56, 20, 78,  5, 29,  5, 18, 74, 42, 68,
       96, 96, 64, 72, 26, 25,  3, 35,  7, 49, 99,  9, 62, 18, 23, 59])>

In [ ]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2579>

In [ ]:
import tensorflow_probability as tfp
tf.math.reduce_variance(tf.cast(e,dtype=tf.float32))
tf.math.reduce_std(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.620964>

In [ ]:
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7041279 , 0.42464495, 0.69981384, 0.67949176, 0.63805664,
       0.05356944, 0.28893244, 0.13932025, 0.36029816, 0.15124178,
       0.9034847 , 0.3545506 , 0.31182992, 0.8890538 , 0.52218604,
       0.75245357, 0.13904512, 0.49873817, 0.39732945, 0.39994264,
       0.9227296 , 0.18214393, 0.16563976, 0.6763464 , 0.03620076,
       0.3651601 , 0.34487367, 0.8468087 , 0.8083445 , 0.33479428,
       0.4720807 , 0.61773205, 0.9428867 , 0.62162197, 0.9719702 ,
       0.49822927, 0.52122426, 0.49367356, 0.07944858, 0.29987395,
       0.30330527, 0.6082425 , 0.50177   , 0.5509056 , 0.4214437 ,
       0.3934945 , 0.41565824, 0.02095747, 0.22201443, 0.1562444 ],
      dtype=float32)>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9719702>

# Squeezinf a tensor

In [ ]:
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7619592 , 0.42692935, 0.00349176, 0.6136968 , 0.02899683,
           0.7336937 , 0.5781324 , 0.3033092 , 0.8271463 , 0.2786157 ,
           0.20009208, 0.17250466, 0.8275186 , 0.9774542 , 0.2585199 ,
           0.05965519, 0.23504758, 0.6951952 , 0.35404193, 0.2759378 ,
           0.5174984 , 0.02692926, 0.10287488, 0.9578552 , 0.80515254,
           0.21705163, 0.48499703, 0.12514043, 0.45123196, 0.7203046 ,
           0.76801276, 0.96232224, 0.2296766 , 0.57091904, 0.8843018 ,
           0.94205904, 0.19204926, 0.47117364, 0.04906619, 0.08419156,
           0.60605836, 0.12055576, 0.86670053, 0.20337677, 0.5663153 ,
           0.9135598 , 0.34963405, 0.28941572, 0.48315942, 0.0947001 ]]]]],
      dtype=float32)>

In [ ]:
G_squ = tf.squeeze(G)
G_squ

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7619592 , 0.42692935, 0.00349176, 0.6136968 , 0.02899683,
       0.7336937 , 0.5781324 , 0.3033092 , 0.8271463 , 0.2786157 ,
       0.20009208, 0.17250466, 0.8275186 , 0.9774542 , 0.2585199 ,
       0.05965519, 0.23504758, 0.6951952 , 0.35404193, 0.2759378 ,
       0.5174984 , 0.02692926, 0.10287488, 0.9578552 , 0.80515254,
       0.21705163, 0.48499703, 0.12514043, 0.45123196, 0.7203046 ,
       0.76801276, 0.96232224, 0.2296766 , 0.57091904, 0.8843018 ,
       0.94205904, 0.19204926, 0.47117364, 0.04906619, 0.08419156,
       0.60605836, 0.12055576, 0.86670053, 0.20337677, 0.5663153 ,
       0.9135598 , 0.34963405, 0.28941572, 0.48315942, 0.0947001 ],
      dtype=float32)>

# One hot bit coding

In [ ]:
someList = [0,1,2,3,4]
tf.one_hot(someList,7)

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(someList,5, on_value ="Yess",off_value="Nooo")

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'Yess', b'Nooo', b'Nooo', b'Nooo'],
       [b'Nooo', b'Yess', b'Nooo', b'Nooo'],
       [b'Nooo', b'Nooo', b'Yess', b'Nooo'],
       [b'Nooo', b'Nooo', b'Nooo', b'Yess'],
       [b'Nooo', b'Nooo', b'Nooo', b'Nooo']], dtype=object)>

#Sq, log sqrt

In [ ]:
H = tf.range(1,20)
H

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 2.9999998 , 3.1622777 ,
       3.3166244 , 3.4641016 , 3.6055508 , 3.7416573 , 3.8729832 ,
       3.9999998 , 4.1231055 , 4.2426405 , 4.358899  ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 ], dtype=float32)>

#Tensor and Numpy

In [ ]:
J = tf.constant(np.array([3,4,5,6]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 5, 6])>

In [ ]:
np.array(J)


array([3, 4, 5, 6])

# Access to GPU

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed May 19 11:00:39 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------